### ISSUE TITLE
would like the option to not verify ssl

### ISSUE THREAD

**Issue by petergtechnologent** [tryfan/ansible-morpheus-collection#11]
Line 54 in morpheus_inventory.py, sslverify is set to True.
In some cases, I want to be able to use this plugin on a morpheus host that does not have a valid certificate, so I have to change that to False.
It would be nice to have the option in the inventory config.

**Comment by tryfan** [comment]
I'll have to update the docs, but there is a `morpheus_ssl_verify` option available for the inventory file.  Set to false and test.

**Comment by petergtechnologent** [comment]
Just to keep the conversation logged, when I do that I still get this:

[WARNING]:  * Failed to parse /var/opt/morpheus/morpheus-
ui/repo/git/731352346aef575b78e1f8cce39f52a7/DM-morpheus-inv-
example/inventory/morpheusinv.yml with auto plugin: [SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)

Inventory file looks like this:

plugin: morpheus_inventory
groups:
  - name: psql
    searchtype: app
    searchstring:
      appname: sonar
      apptier: psql
  - name: elastic
    searchtype: app
    searchstring:
      appname: sonar
      apptier: elastic
  - name: sonar
    searchtype: app
    searchstring:
      appname: sonar
      apptier: sonar
morpheus_url: 'https://localhost'
morpheus_ssl_verify: false
morpheus_api_key: <mykey>

**Comment by petergtechnologent** [comment]
The github text editor did a weird thing there with the bullets, but its right, I promise.

**Comment by tryfan** [comment]
fixed in 0.1.1
