### ISSUE TITLE
packaging module not found

### ISSUE THREAD

**Issue by petergtechnologent** [tryfan/ansible-morpheus-collection#12]
On a default all in one Morpheus 4.2.3 instance, when using this inventory plugin, I get an error:
[WARNING]:  * Failed to parse /var/opt/morpheus/morpheus-
ui/repo/git/731352346aef575b78e1f8cce39f52a7/DM-morpheus-inv-
example/inventory/morpheusinv.yml with auto plugin: No module named packaging

This is because you do "from packaging import version" but the system does not have the packaging module installed.

I fixed with:
yum install python-pip -y
pip install packaging

I think this is just a documentation update though I would love to see morpheus lay this down as a part of its installer to make using this plugin easier.

**Comment by petergtechnologent** [comment]
I am on centos 7.9 running morpheus 4.2.3
Need to test if the same things are true on a different OS or with Morpheus 5.2.0

**Comment by petergtechnologent** [comment]
Also, I am using the built in Ansible 2.9.15 version that comes with Morpheus 4.2.3.

**Comment by tryfan** [comment]
On CentOS 7.8, the packaging module is required for ansible-galaxy to work properly, so I think leaving packaging in is appropriate.  It's totally possible I'm missing something though, so please let me know.

**Comment by petergtechnologent** [comment]
I think leaving packaging is fine if the documentation is updated to say you have to run the pip install on the morpheus server.
I don't know that your statement of ansible-galaxy needing it to work is true though. I haven't tested thoroughly, but I was using ansible-galaxy to get community modules  and had no trouble even though I didn't have this module installed. 
Moreso, I don't use ansible galaxy to get your inventory plugin as I am on ansible 2.9. So there's no reason to assume, I don't think, that a user would have ansible-galaxy installed and working to use your inventory plugin. 

Also, just as a side note, I see the new version tag but don't see the documentation update for the morpheus command bus enablement in the ansible integration call out.

**Comment by tryfan** [comment]
I'll switch it out since less non-base deps are better anyway.  I'll slot it into the next version
