### ISSUE TITLE
Sonarqube installation with Ansible - Execution from Automation

### ISSUE THREAD

**Issue by sukanya-dm** [tryfan/ansible-morpheus-collection#15]
**Description:**
Executed the task in Automation section
Postgres was installed successfully, and ended up with error while installing elasticsearch.
Please find the attached log information along with the other required details like architecture, blueprint information, versions used etc. in the attachment, 'Sonarqube.from.Automation.docx'.

[Sonarqube from Automation.docx](https://github.com/tryfan/ansible-morpheus-collection/files/5622012/Sonarqube.from.Automation.docx)
[Execution logs from Automation.txt](https://github.com/tryfan/ansible-morpheus-collection/files/5622013/Execution.logs.from.Automation.txt)

**Comment by tryfan** [comment]
Closed after discussion with Ernesto and Peter
