### ISSUE TITLE
Sonarqube installation using Ansible- Execution from instances

### ISSUE THREAD

**Issue by sukanya-dm** [tryfan/ansible-morpheus-collection#16]
Description:
Task 1: Executed the task from Elastic instance
Elastic search and sonar was installed in all of elastic nodes. All the services are up and running. But sonar was not installed on sonar nodes, instead it got installed in elastic nodes. Also, please find the complete execution log which was executed from elastic instance in Morpheus console as an attachment, 'Execution logs from Elastic instance.txt'

Task 2: Executed the task from Sonar instance
Sonarqube is not getting installed in sonar nodes due to connection issue with Postgres. Please find the complete execution log which was executed from sonar instance in Morpheus console as an attachment, 'Execution logs from Sonar instance.txt'

Also find the other required details like architecture, blueprint information, versions used etc in the attachment, 'Sonarqube.-.Execution.from.Instances.docx'.

[Execution logs from Elastic instance.txt](https://github.com/tryfan/ansible-morpheus-collection/files/5622376/Execution.logs.from.Elastic.instance.txt)
[Execution from Sonar instance.txt](https://github.com/tryfan/ansible-morpheus-collection/files/5622377/Execution.from.Sonar.instance.txt)
[Sonarqube - Execution from Instances.docx](https://github.com/tryfan/ansible-morpheus-collection/files/5622378/Sonarqube.-.Execution.from.Instances.docx)

**Comment by tryfan** [comment]
Closed after discussion with Ernesto and Peter
