### ISSUE TITLE
option to exclude hosts from unassigned group

### ISSUE THREAD

**Issue by cuxtud** [tryfan/ansible-morpheus-collection#20]
Something like: include_unassigned: False

If hosts is set to all in play then it is executed on all groups, including unassigned

**Comment by tryfan** [comment]
Sorry @cuxtud, this completely slipped my mind.   

I was testing with the plugin, and looked through our previous messages.  The [unassigned] group does not come from this plugin.  It's coming from Morpheus itself.  Using this as the inventory source shouldn't include any unassigned group.

**Comment by tryfan** [comment]
closing this, unless there's some way to show it's coming from this plugin

**Comment by cuxtud** [comment]
All good. The unassigned group doesnt comeup when anisble-inventory --list is run from the app server. It comes up when playbook is executed.

**Comment by tryfan** [comment]
Morpheus still adds it's own inventory, since ansible supports multiple `-i` options.
