### ISSUE TITLE
Dynamic Inventory hosts details are not fetched

### ISSUE THREAD

**Issue by baba-dude** [tryfan/ansible-morpheus-collection#28]
Hi,
Thanks for this solution and all the effort. it really helps us a lot. I have followed the steps mentioned but i'm unable to see the hosts in the morpheus ansible inventory ?
Could you please assist if there is anything else to be done.

**Comment by tryfan** [comment]
Can you post the output of the following:
`ansible-doc -t inventory -l | grep morpheus`
`ansible-inventory -i <your inventory file> --list`

Also, can you post your inventory file with the creds removed?

**Comment by baba-dude** [comment]
Thanks for the response..!  Please find the details below.
![image](https://user-images.githubusercontent.com/38130277/136030556-8ab29d00-32fd-4375-a558-495860c7c32d.png)

morpheusinv.yml file
plugin: morpheus_inventory
groups: 
  - searchtype: tag
    searchstring:
      tagName: type
      tagValue: cloud
morpheus_url: https://********

**Comment by tryfan** [comment]
`morpheus_api_key` is missing from your inventory.  The README is a little unclear on the API token point.  If you're running ansible from morpheus in a context that supplies an API key, Ansible will use that in this plugin.  If running outside of Morpheus or the context doesn't supply an API key, you must provide one in the inventory file with `morpheus_api_key`  You can test this by putting one into the file and running the `ansible-inventory` command again.

**Comment by baba-dude** [comment]
Thanks for the quick response. Could you please help me out in fetching API Key from Morpheus ? I tried but couldnt find a solution .

**Comment by tryfan** [comment]
Those instructions are located here: https://docs.morpheusdata.com/en/latest/administration/user_settings/user_settings.html#api-access

**Comment by baba-dude** [comment]
Still No Luck..! 
plugin: morpheus_inventory
groups:
  - searchtype: name
    searchstring: azure
morpheus_url: https://*****
morpheus_api_key: *******

![image](https://user-images.githubusercontent.com/38130277/136036793-81151b50-b08b-4dda-9261-44bcaad2b880.png)

**Comment by tryfan** [comment]
The error says you have a problem with SSL.  There is a variable in the README of this repository to deal with that.  The way you are trying to test with morpheus isn't valid.  That run box only takes arguments for the ansible command itself. 

 It also looks like you have permissions issues in your `/opt/morpheus/.local`  I searched this at support.morpheusdata.com and found this: https://support.morpheusdata.com/s/article/Error-messages-received-when?language=en_US

**Comment by baba-dude** [comment]
Thanks for your inputs..! permission issue is resolved and I've added SSL parameter in the inventory file. But still the error persists.
![image](https://user-images.githubusercontent.com/38130277/136056284-98bae410-bf51-4e33-9352-15e10971b170.png)

**Comment by baba-dude** [comment]
Finally, Got something out here..!
![image](https://user-images.githubusercontent.com/38130277/136058315-1cf59da4-b78a-4ce3-aac4-615a4f31d569.png)

**Comment by baba-dude** [comment]
I just tried to trigger a work flow but no Luck..!
![image](https://user-images.githubusercontent.com/38130277/136063935-81893c38-886f-426a-9c55-eda5d630c665.png)

**Comment by tryfan** [comment]
The way I run tasks that need dynamic inventory is the "Command Options" in the task definition.  I do `-i <inventory file>`  Happy to hear the plugin is working for you.

**Comment by tryfan** [comment]
In the doc, it says "This plugin requires the Morpheus agent on target hosts due to credential storage methods in Morpheus."  I will make it clearer.  This plugin works with the Morpheus command bus, and it looks like you don't have that checked in your ansible integration.  

I've tried to answer many questions in this issue, but the plugin appears to be functioning properly.  I am going to close this issue.

**Comment by baba-dude** [comment]
I'm sorry for asking multiple questions and bothering you. Since I'm pretty new to Morpheus its getting difficult. I have enabled command bus check box when i integrated Morpheus. How do we check if the Morpheus agent is running on target nodes ?
