### ISSUE TITLE
dynamic inventory enhancement

### ISSUE THREAD

**Issue by cuxtud** [tryfan/ansible-morpheus-collection#6]
Read inventory of a cloud in morpheus and if VM is managed or discovered, add them to inventory and create groups based on discovered tags and platform.

group names for tags as _key_value_ and platform as _os_platform_

**Comment by tryfan** [comment]
Can you give me some examples of os_platform?

**Comment by tryfan** [comment]
For the tags, do you mean remote cloud platform tags or Morpheus labels?

**Comment by cuxtud** [comment]
> Can you give me some examples of os_platform?

this is the value of morpheus variable morpheus['server']['platform']
eg: centos, ubuntu

**Comment by cuxtud** [comment]
> For the tags, do you mean remote cloud platform tags or Morpheus labels?

remote cloud platform tags

**Comment by tryfan** [comment]
Ok, let me see what I can do.

**Comment by tryfan** [comment]
@cuxtud Within Morpheus, this plugin currently only works with managed instances that have the agent installed
