### ISSUE TITLE
target groups of morpheus ansible inventory in plays/roles

### ISSUE THREAD

**Issue by cuxtud** [tryfan/ansible-morpheus-collection#7]
like _key_value[0]_

**Comment by tryfan** [comment]
Is this part of #6 but you want to target the first VM in the list?

**Comment by cuxtud** [comment]
> Is this part of #6 but you want to target the first VM in the list?

yep canbe clubbed to #6 should be able to target one or range or many like _[0] [0-2] [0,1,3]_

**Comment by tryfan** [comment]
What is the source of truth on the order?  If running a DB play, you may want to select the master, in which case you designate one.  If you have an arbitrary list, selecting group[0] will give you the first one. 

eg. https://github.com/tryfan/ansible-role-rabbitmq-cluster/blob/master/tasks/rabbitmq_ha_config.yml
